const translations = {
  de: {
    title: 'Schnabelglück', description: 'Ein kleiner Pelikan. Ein großes Abenteuer. Tauche nach Fischen und entdecke deine neue Lieblingspause.', desktopNote: 'Ein bisschen Meer.<br>Ein bisschen mehr Glück.', edition: 'DEINE KLEINE AUSZEIT · 01', footerBrand: 'MIT LIEBE ZUM MEER.', footerControls: 'HALTEN ↓ TAUCHEN · LOSLASSEN ↑ FLIEGEN',
    app: 'Schnabelglück Spiel', canvas: 'Küstenwelt. Halten oder Leertaste zum Tauchen, loslassen zum Fliegen.', pause: 'Spiel pausieren', settings: 'Einstellungen öffnen',
    tagline: 'Kleiner Vogel. Großes Abenteuer.', hero: 'Hey, ich bin Pip!', recordLabel: '✧ FRÜHERER RUNDENREKORD', points: 'PUNKTE', stage: 'Etappe wählen',
    play: 'Los gehts!', continue: 'Weiter gehts!', language: 'Sprache',
    catch: 'DEIN FANG', hud: 'Spielstand', status: 'Pips Energie und Tauchluft', energy: 'ENERGIE', air: 'LUFT', airTrack: 'Verbleibende Tauchluft in Sekunden', surface: 'AUFTAUCHEN', locales: { de: 'Deutsch', en: 'Englisch', es: 'Spanisch' },
    pauseKicker: 'KLEINE VERSCHNAUFPAUSE', pauseTitle: 'Meer läuft<br>dir nicht weg.', pauseText: 'Pip wartet auf dich.', resume: 'Weiterfliegen', quit: 'Runde beenden',
    settingsKicker: 'GANZ DEIN TEMPO', settingsTitle: 'Wie klingt<br>dein Meer?', close: 'Schließen', music: 'Musik', sound: 'Meeresrauschen & Sounds', haptics: 'Vibration',
    settingsHelp: 'Halten zum Tauchen, loslassen zum Fliegen.<br>Folge den Fischbögen unter Wasser, wähle deine Tiefe und tauche rechtzeitig zum Durchatmen auf. Goldfische belohnen freiwilliges Risiko.<br>Je länger Pips Reise dauert, desto schneller und dichter werden die Begegnungen.<br>Jeder Fisch gibt Punkte und Energie – auch bei vollem Schnabel. Zusammenstöße kosten Energie; Felsen und Luftmangel beenden die Runde.<br>Nach dem Auftauchen: 2× tippen für einen Überschlag, 3× für einen doppelten. Triff dabei eine Möwe für +75.<br>Am Computer: Maus oder Leertaste. Escape pausiert.', settingsDone: 'Alles klar',
    resultKicker: 'DAS WAR EINE SCHÖNE RUNDE', resultTitle: 'Schnabel voll.<br>Herz auch.', fish: 'Fische', combo: 'Beste Fangserie', seaTime: 'Meereszeit', retry: 'Speichern erneut versuchen', next: 'Zum nächsten Nest', again: 'Eine Runde geht noch', home: 'Zurück an den Strand',
    install: 'App installieren', update: 'Updates prüfen', installTitle: 'Auf deinem Handy installieren', installHelp: 'Android: Im normalen Chrome-Menü ⋮ → Zum Startbildschirm hinzufügen → Installieren.<br><br>iPhone: In Safari Teilen → Zum Home-Bildschirm.<br><br>Im Inkognito-Modus ist die Installation nicht verfügbar.', understood: 'Verstanden',
    stages: ['Geschützte Bucht', 'Fischerhafen', 'Korallenriff'], locked: 'noch verschlossen', best: 'Rekord: {score} Punkte',
    reasons: { puffer: 'Ein aufgeblasener Kugelfisch!', island: 'Die Insel erwischt!', reef: 'Am Felsen hängen geblieben!', buoy: 'Eine Boje erwischt!', coral: 'An den Korallen hängen geblieben!', diver: 'Taucher voraus!', harpoon: 'Von der Harpune erwischt!', surfer: 'Surfer voraus!', gull: 'Möwe im Anflug!', jelly: 'Eine Qualle erwischt!', driftwood: 'Treibholz voraus!', air: 'Die Luft ist aus!', shark: 'Vom Hai erwischt!', net: 'Im Netz gelandet!', fisher: 'Fischer voraus!', energy: 'Keine Energie mehr!', complete: 'Willkommen im Nest!', final: 'Alle Küken satt. Herz auch.', fallback: 'Bis zur nächsten Runde!' },
    nestReached: 'NEST ERREICHT', allNests: 'ALLE NESTER ERREICHT', newRecord: 'NEUER ETAPPENREKORD', mission: '✦ Tauchmission geschafft! +100 Punkte', nextGoal: 'Nächstes Ziel: 5 Fische in einem Tauchgang.', finalMission: 'Pip hat alle drei Nester erreicht. Besuche deine Lieblingsbucht wieder!', nextMission: 'Weiter zum {stage}.', saved: 'Dein Fortschritt ist gespeichert.', saveFailed: 'Dein Fortschritt konnte nicht gespeichert werden.', settingsSaveFailed: 'Deine Einstellung konnte gerade nicht gespeichert werden.',
    updateReady: 'Update verfügbar · neu laden', updateLoading: 'Update wird geladen …', updateChecking: 'Update wird geprüft …', offlinePreparing: 'Offline-Modus wird noch vorbereitet.', updateLoaded: 'Update wird geladen. Bitte die App geöffnet lassen.', updateNow: 'Update bereit. Jetzt neu laden.', upToDate: 'Deine App ist auf dem aktuellen Stand.', updateFailed: 'Update-Prüfung fehlgeschlagen. Bitte die Internetverbindung prüfen.', updateMenu: 'Update bereit – im Startmenü neu laden.', updateUnavailable: 'Update konnte nicht geladen werden. Bitte erneut prüfen.', offlineUnavailable: 'Offline-Modus gerade nicht verfügbar.'
  },
  en: {
    title: 'Happy Beak', description: 'A little pelican. A big adventure. Dive for fish and discover your new favorite break.', desktopNote: 'A little sea.<br>A little more joy.', edition: 'YOUR LITTLE BREAK · 01', footerBrand: 'MADE WITH LOVE FOR THE SEA.', footerControls: 'HOLD ↓ DIVE · RELEASE ↑ FLY',
    app: 'Happy Beak game', canvas: 'Coastal world. Hold or press Space to dive; release to fly.', pause: 'Pause game', settings: 'Open settings',
    tagline: 'Little bird. Big adventure.', hero: 'Hi, I’m Pip!', recordLabel: '✧ PREVIOUS ROUND RECORD', points: 'POINTS', stage: 'Choose stage', play: 'Let’s go!', continue: 'Keep going!', language: 'Language',
    catch: 'YOUR CATCH', hud: 'Game status', status: 'Pip’s energy and diving air', energy: 'ENERGY', air: 'AIR', airTrack: 'Remaining diving air in seconds', surface: 'SURFACE', locales: { de: 'German', en: 'English', es: 'Spanish' },
    pauseKicker: 'A LITTLE BREATHER', pauseTitle: 'The sea won’t<br>go anywhere.', pauseText: 'Pip is waiting for you.', resume: 'Keep flying', quit: 'End round',
    settingsKicker: 'AT YOUR OWN PACE', settingsTitle: 'How does<br>your sea sound?', close: 'Close', music: 'Music', sound: 'Sea sounds & effects', haptics: 'Vibration',
    settingsHelp: 'Hold to dive, release to fly.<br>Follow the arcs of fish underwater, pick your depth, and surface in time to breathe. Golden fish reward voluntary risk.<br>The longer Pip travels, the faster and denser encounters become.<br>Every fish gives points and energy—even with a full beak. Collisions cost energy; rocks and running out of air end the round.<br>After surfacing: tap 2× for a flip, 3× for a double. Hit a gull for +75.<br>On a computer: use mouse or Space. Escape pauses.', settingsDone: 'Got it',
    resultKicker: 'THAT WAS A LOVELY ROUND', resultTitle: 'Beak full.<br>Heart too.', fish: 'Fish', combo: 'Best catch streak', seaTime: 'Sea time', retry: 'Try saving again', next: 'To the next nest', again: 'One more round', home: 'Back to the beach',
    install: 'Install app', update: 'Check for updates', installTitle: 'Install on your phone', installHelp: 'Android: In Chrome’s regular menu ⋮ → Add to Home screen → Install.<br><br>iPhone: In Safari, Share → Add to Home Screen.<br><br>Installation is unavailable in Incognito mode.', understood: 'Got it',
    stages: ['Sheltered Bay', 'Fishing Harbor', 'Coral Reef'], locked: 'still locked', best: 'Record: {score} points',
    reasons: { puffer: 'An inflated pufferfish!', island: 'The island got you!', reef: 'Caught on the reef!', buoy: 'Hit a buoy!', coral: 'Caught in the coral!', diver: 'Diver ahead!', harpoon: 'Hit by a harpoon!', surfer: 'Surfer ahead!', gull: 'A gull is coming in!', jelly: 'Hit a jellyfish!', driftwood: 'Driftwood ahead!', air: 'You’re out of air!', shark: 'Caught by a shark!', net: 'Caught in a net!', fisher: 'Fisher ahead!', energy: 'No energy left!', complete: 'Welcome to the nest!', final: 'All chicks fed. Heart full.', fallback: 'Until the next round!' },
    nestReached: 'NEST REACHED', allNests: 'ALL NESTS REACHED', newRecord: 'NEW STAGE RECORD', mission: '✦ Dive mission complete! +100 points', nextGoal: 'Next goal: 5 fish in one dive.', finalMission: 'Pip reached all three nests. Visit your favorite bay again!', nextMission: 'On to {stage}.', saved: 'Your progress is saved.', saveFailed: 'Your progress could not be saved.', settingsSaveFailed: 'Your setting could not be saved right now.',
    updateReady: 'Update available · reload', updateLoading: 'Loading update …', updateChecking: 'Checking for updates …', offlinePreparing: 'Offline mode is still getting ready.', updateLoaded: 'Update is downloading. Please keep the app open.', updateNow: 'Update ready. Reload now.', upToDate: 'Your app is up to date.', updateFailed: 'Update check failed. Please check your internet connection.', updateMenu: 'Update ready — reload from the start menu.', updateUnavailable: 'Update could not be loaded. Please try again.', offlineUnavailable: 'Offline mode is unavailable right now.'
  },
  es: {
    title: 'Pico Feliz', description: 'Un pequeño pelícano. Una gran aventura. Sumérgete por peces y descubre tu nuevo descanso favorito.', desktopNote: 'Un poco de mar.<br>Un poco más de alegría.', edition: 'TU PEQUEÑO DESCANSO · 01', footerBrand: 'HECHO CON AMOR POR EL MAR.', footerControls: 'MANTÉN ↓ BUCEA · SUELTA ↑ VUELA',
    app: 'Juego Pico Feliz', canvas: 'Mundo costero. Mantén pulsado o usa Espacio para bucear; suelta para volar.', pause: 'Pausar juego', settings: 'Abrir ajustes',
    tagline: 'Pájaro pequeño. Gran aventura.', hero: '¡Hola, soy Pip!', recordLabel: '✧ RÉCORD DE LA RONDA ANTERIOR', points: 'PUNTOS', stage: 'Elegir etapa', play: '¡Vamos!', continue: '¡Sigue así!', language: 'Idioma',
    catch: 'TU PESCA', hud: 'Estado del juego', status: 'Energía y aire de buceo de Pip', energy: 'ENERGÍA', air: 'AIRE', airTrack: 'Aire de buceo restante en segundos', surface: 'SUBE', locales: { de: 'Alemán', en: 'Inglés', es: 'Español' },
    pauseKicker: 'UN PEQUEÑO RESPIRO', pauseTitle: 'El mar no<br>se irá a ningún lado.', pauseText: 'Pip te espera.', resume: 'Seguir volando', quit: 'Terminar ronda',
    settingsKicker: 'A TU RITMO', settingsTitle: '¿Cómo suena<br>tu mar?', close: 'Cerrar', music: 'Música', sound: 'Mar y efectos', haptics: 'Vibración',
    settingsHelp: 'Mantén pulsado para bucear y suelta para volar.<br>Sigue los arcos de peces bajo el agua, elige tu profundidad y sube a tiempo para respirar. Los peces dorados premian el riesgo voluntario.<br>Cuanto más dure el viaje de Pip, más rápidos y densos serán los encuentros.<br>Cada pez da puntos y energía, incluso con el pico lleno. Los choques restan energía; las rocas y la falta de aire terminan la ronda.<br>Al salir del agua: toca 2× para una voltereta, 3× para una doble. Golpea a una gaviota para +75.<br>En ordenador: ratón o Espacio. Escape pausa.', settingsDone: 'Entendido',
    resultKicker: 'HA SIDO UNA BONITA RONDA', resultTitle: 'Pico lleno.<br>Corazón también.', fish: 'Peces', combo: 'Mejor racha', seaTime: 'Tiempo en el mar', retry: 'Intentar guardar de nuevo', next: 'Al siguiente nido', again: 'Una ronda más', home: 'Volver a la playa',
    install: 'Instalar aplicación', update: 'Buscar actualizaciones', installTitle: 'Instala en tu móvil', installHelp: 'Android: En el menú normal de Chrome ⋮ → Añadir a la pantalla de inicio → Instalar.<br><br>iPhone: En Safari, Compartir → Añadir a pantalla de inicio.<br><br>La instalación no está disponible en modo incógnito.', understood: 'Entendido',
    stages: ['Bahía protegida', 'Puerto pesquero', 'Arrecife de coral'], locked: 'aún bloqueada', best: 'Récord: {score} puntos',
    reasons: { puffer: '¡Un pez globo inflado!', island: '¡La isla te atrapó!', reef: '¡Atrapado en el arrecife!', buoy: '¡Golpeaste una boya!', coral: '¡Atrapado en el coral!', diver: '¡Buzo delante!', harpoon: '¡Te alcanzó un arpón!', surfer: '¡Surfista delante!', gull: '¡Gaviota a la vista!', jelly: '¡Te alcanzó una medusa!', driftwood: '¡Madera a la deriva delante!', air: '¡Te quedaste sin aire!', shark: '¡Te atrapó un tiburón!', net: '¡Caíste en una red!', fisher: '¡Pescador delante!', energy: '¡No queda energía!', complete: '¡Bienvenido al nido!', final: 'Todas las crías alimentadas. Corazón lleno.', fallback: '¡Hasta la próxima ronda!' },
    nestReached: 'NIDO ALCANZADO', allNests: 'TODOS LOS NIDOS ALCANZADOS', newRecord: 'NUEVO RÉCORD DE ETAPA', mission: '✦ ¡Misión de buceo lograda! +100 puntos', nextGoal: 'Siguiente meta: 5 peces en una inmersión.', finalMission: 'Pip llegó a los tres nidos. ¡Vuelve a tu bahía favorita!', nextMission: 'Sigue hacia {stage}.', saved: 'Tu progreso está guardado.', saveFailed: 'Tu progreso no se pudo guardar.', settingsSaveFailed: 'No se pudo guardar tu ajuste ahora.',
    updateReady: 'Actualización disponible · recargar', updateLoading: 'Cargando actualización …', updateChecking: 'Buscando actualizaciones …', offlinePreparing: 'El modo sin conexión se está preparando.', updateLoaded: 'La actualización se está descargando. Mantén la aplicación abierta.', updateNow: 'Actualización lista. Recarga ahora.', upToDate: 'Tu aplicación está actualizada.', updateFailed: 'La búsqueda de actualización falló. Revisa tu conexión a internet.', updateMenu: 'Actualización lista — recarga desde el menú inicial.', updateUnavailable: 'No se pudo cargar la actualización. Inténtalo de nuevo.', offlineUnavailable: 'El modo sin conexión no está disponible ahora.'
  }
};

export const locales = ['de', 'en', 'es'];
export const localeFrom = value => locales.includes(value) ? value : 'de';
let locale = 'de';
export function setLocale(value) { locale = localeFrom(value); return locale; }
export function currentLocale() { return locale; }
export function t(key, values = {}) {
  const value = key.split('.').reduce((entry, part) => entry?.[part], translations[locale]) ?? key;
  return String(value).replace(/\{(\w+)\}/g, (_, name) => values[name] ?? '');
}
export function stageName(index) { return translations[locale].stages[index] ?? ''; }
export function formatNumber(value) { return Number(value).toLocaleString(locale); }
export function applyTranslations() {
  document.documentElement.lang = locale;
  document.title = t('title');
  document.querySelector('meta[name="description"]')?.setAttribute('content', t('description'));
  for (const element of document.querySelectorAll('[data-i18n]')) element.textContent = t(element.dataset.i18n);
  for (const element of document.querySelectorAll('[data-i18n-html]')) element.innerHTML = t(element.dataset.i18nHtml);
  for (const element of document.querySelectorAll('[data-i18n-aria-label]')) element.setAttribute('aria-label', t(element.dataset.i18nAriaLabel));
}
